apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multi-user-app
  name: multi-user-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-user-app
  template:
    metadata:
      labels:
        app: multi-user-app
    spec:
      containers:
      - image: jayanthroyg/multi-user-system:latest
        imagePullPolicy: Always
        name: multi-user-system
        ports:
        - containerPort: 8000
