apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-04-03T11:41:15Z"
  generation: 4
  labels:
    app: multi-user-app
  name: multi-user-app
  namespace: default
  resourceVersion: "200779"
  uid: 120decf7-f23c-4354-899c-3394450f13dd
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: multi-user-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: multi-user-app
    spec:
      containers:
      - image: jayanthroyg/multi-user-system:latest
        imagePullPolicy: Always
        name: multi-user-system
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-04-04T04:21:08Z"
    lastUpdateTime: "2025-04-04T04:21:08Z"
    message: ReplicaSet "multi-user-app-795f74fc78" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-04-04T09:43:04Z"
    lastUpdateTime: "2025-04-04T09:43:04Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
