apiVersion: v1
kind: Service
metadata:
  labels:
    app: multi-user-app
  name: multi-user-app
  namespace: default
spec:
  ports:
  - nodePort: 31394
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: multi-user-app
  type: NodePort
